### ISSUE TITLE
Removal/migration of linksbot

### ISSUE THREAD

**Issue by brycied00d** [errbotio/errbot-version-server#2]
You should know that I've deleted my fork of the original https://github.com/vaz-ar/err-linksBot linksBot plugin. It appears that @vaz-ar deleted the original repo which left me with the only remaining fork, which @gbin then referenced/linked-to. However I am not the authoritative developer of this plugin, just someone who forked to submit a PR to its original author. Since I no longer use this plugin, and its author has "disowned" it, I've deleted my fork.

@sparunakian has cloned the repo and is updating the plugin, perhaps they should be referenced? 
https://github.com/sparunakian/err-linksBot/

**Comment by sijis** [comment]
This should have probably gone against the [errbotio/errbot ](https://github.com/errbotio/errbot) repo. Either way, we have a utility that updates the plugins list. I do not know how often its done, however, when it does run, it should remove all references and only show the latest err-linksBot repo available.
